name: Auto-update
author: Thibault Derousseaux <tibdex@gmail.com>
description: Automatically keep pull requests with auto-merged enabled up to date with their base branch.
inputs:
  ignore_auto_merge:
    description: When this is false only PRs with auto-merge enabled will be updated. Setting to true will cause all PRs to be updated.
    default: false
  github_token:
    description: Token for the GitHub API.
    default: ${{ github.token }}
outputs:
  unmerged_pr:
    description: The PR that could not be merged automatically.
runs:
  using: node20
  main: dist/index.js
branding:
  icon: refresh-cw
  color: blue
